### ISSUE TITLE
Add a simpler format of hashed passphrase for license generation 

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-lcp-server#180]
See issue #179 and the updated License server documentation. Add `hex_value` as a simpler variant of hashed passphrased in a partial license.

**Comment by danielweck** [comment]
https://github.com/readium/readium-lcp-server/blob/e1bd48f6519b75c28c54b68d4ebe28e43c166900/license/license.go#L36-L41

Ideally, the proposed additional `HexValue` field in the `UserKey` struct would use a "byte array" type (instead of a string of 64 characters representing the hexadecimal digest encoding of a 32-bytes/256-bit SHA256 hash). This way, consumer code does not have to explicitly decode from hex to binary buffer.

For `Encryption.UserKey.Value` of type `byte[]`, Go JSON marshalling automatically uses Base64 (see  https://golang.org/pkg/encoding/json/ ), which we want to avoid for `Encryption.UserKey.HexValue`.
One solution would be to create a subtype of `[]byte` that implements custom marshalling interfaces ( https://golang.org/src/encoding/encoding.go ). For example (quick implementation, not tested):

```go
type HexStringByteArray []byte

func (arr HexStringByteArray) MarshalText() (text []byte, err error) {

    str, err := hex.EncodeString(arr[:])
    if err != nil 
        return nil, err
    }

   return str[:], nil
}

func (arr *HexStringByteArray) UnmarshalText(text []byte) error {
    var b []byte
    
    b, err := hex.DecodeString(text[:])
    if err != nil 
        return err
    }

   *arr = b[:]
   return nil
}
```

```go
type UserKey struct {
...
    Value HexStringByteArray `json:"hex_value,omitempty"`
}
```

**Comment by danielweck** [comment]
To facilitate backward-compatibility, at first it seems that we could just use the existing struct field `Encryption.UserKey.Value` with type `HexStringOrBase64ByteArray` instead of `byte[]`:

```go
type UserKey struct {
...
    Value HexStringOrBase64ByteArray `json:"value,omitempty"`
}
```

...and "detect" inside the `UnmarshalText()` function whether the passed text is Base64 (in which case use`base64.StdEncoding.DecodeString()`) or hex (in which case use`hex.DecodeString()`), both resulting in the correct `byte[]` output.
A potential problem with this design approach is that we do not have enough information to decide what to use for the reverse `MarshalText()` operation, i.e. to convert from `byte[]` to either `base64.StdEncoding.EncodeToString()` or `hex.EncodeString()`. That being said, the `Encryption.UserKey.Value` field is always deserialized from JSON, but never actually serialized back into JSON, so I think this would work just fine (we would just need to document this clearly in the Go source, to avoid confusing future developers / code reviewers).

Thoughts?
@jpbougie etc.

**Comment by llemeurfr** [comment]
I tried and tested this simple solution in #182. The added HexValue in UserKey is a transient string, quickly mapped back to Value (byte array). backward compat. is guaranteed (via the use of the 'value' json param) and new developers are encouraged to use 'hex_value' (json param) instead.

For review.

**Comment by jpbougie** [comment]
The main issue I see is that hex-encoding will almost always work as a base64, and you technically could have a base64 string that would only use the 0-9 and a-f characters, and thus be recognized as a valid hex-string.

I would rather use a solution like Laurent's where we clearly delimitate the encoding we expect from a value.

**Comment by llemeurfr** [comment]
ok, therefore "sold", PR merged, ready for use on the develop branch (with a test on the size of the incoming Value = 32 to avoid some weird error messages).
