### ISSUE TITLE
Encryption logic fails when files in the EPUB has % in the file name.

### ISSUE THREAD

**Issue by dozer75** [readium/readium-lcp-server#302]
When an EPUB file contains a file that is about to be encrypted (e.g. image) that contains a % (percent sign) the encryption logic fails. The lcpencrypt application fails with the message `Error encrypting  OEBPS/Images/33660Vinometer0-25%_fmt.gif :  parse "OEBPS/Images/33660Vinometer0-25%_fmt.gif": invalid URL escape "%_f"` .

File names with % is allowed (even though very unfortunate) so the encryption logic should be able to handle this.

**Comment by llemeurfr** [comment]
The origin of the issue is in 

https://github.com/readium/readium-lcp-server/blob/master/pack/pack.go#L229-L233
and
https://github.com/readium/readium-lcp-server/blob/master/xmlenc/encryption.go#L28-L33

But modifying that part cannot be done without verifying that client modules will be able to de-espace the path correctly in encryption.xml.

**Comment by llemeurfr** [comment]
The code of the readium toolkits was checked , URI's are properly escaped there.
