### ISSUE TITLE
No WAL for sqlite

### ISSUE THREAD

**Issue by robertkeizer** [readium/readium-lcp-server#313]
Greetings!

Recently I've had reason to modify the `readium-lcp-server` system so that the default `sqlite3` driver can be used without automatically enabling `WAL` mode. My solution was to simply create a diff that can be applied to the `1.7.0` tag that comments out the conditional statements where ` db.Exec("PRAGMA journal_mode = WAL")` is used.

I'd like to contribute back to the project, and more generally make this an option that can be enabled by way of an environment variable or configuration file entry. After going through the source code a bit I've noted that the current configuration uses a string for the `Database` ( [this line in config](https://github.com/readium/readium-lcp-server/blob/master/config/config.go#L43) ).

On the outset it doesn't seem particularly nice to create a new top level configuration option, and similarly I don't think it would be wise ( perhaps someone will dispute this and correct me ) to modify the format of the `database` option. Given this, I'm wondering if others agree that the best approach would be to check whether an environment variable is set [here](https://github.com/readium/readium-lcp-server/blob/master/frontend/frontend.go#L59), [here](https://github.com/readium/readium-lcp-server/blob/master/lcpserver/lcpserver.go#L66), and [here](https://github.com/readium/readium-lcp-server/blob/master/lsdserver/lsdserver.go#L63) and simply bypass these statements.

Any suggestions or feedback would be most welcome! Thanks in advance.

**Comment by robertkeizer** [comment]
@llemeurfr - happy to have this sit on the bottom of my list, I'm just hesitant to put in time for a change if it isn't wanted, etc.

**Comment by llemeurfr** [comment]
Hi @robertkeizer - the WAL mode was activated for sqlite at the start of the project, a long time ago. I guess that the goal was to optimize the db for speed. 

If this is causing issues in some circumstances (it would be interesting for the community to know why), we can think about a way to invalidate it. As you say it can be done via the configuration file or via an environment variable. 

Currently the only environment variables are the paths of the config files for the different servers. Users would therefore be surprised if we introduce a new env variable. 
We could also act on the config file. I agree that it would not be wise to modify the format of the `database` param. 

Alternatively we could add an optional config param in the "lcp:" "lsd:" and "frontend:" sections of the config file(s).  
This boolean param could be named "sqlite-no-wal" (so that by default nothing is modified) and it would be easy to use it in the codebase for skipping the `"PRAGMA journal_mode = WAL"` directive. 

Would you agree with this evolution?

**Comment by atomotic** [comment]
Why not set the journal mode in the [connection string](https://github.com/readium/readium-lcp-server/blob/master/test/config.yaml#L31)?


https://github.com/mattn/go-sqlite3#connection-string
<img width="854" alt="image" src="https://user-images.githubusercontent.com/67420/228775021-ccca6f78-c8ba-4d36-a89b-cdd7ca5b2b3b.png">

**Comment by llemeurfr** [comment]
Oh this is interesting! 
If we use that we have to be careful about backward compatibility. If no `_journal` or `_journal_mode`is found in the DSN, the existing pragma must be kept so that existing lcp servers using sqlite (and WAL) are not impacted.

**Comment by llemeurfr** [comment]
The simplest is the addition of this test before applying the pragma command:

`	if driver == "sqlite3" && !strings.Contains(cnxn, "_journal") {`
	`	_, err = db.Exec("PRAGMA journal_mode = WAL")`

This works for both `_journal` and `_journal_mode`. The risk to have a false match ("_journal" elsewhere in the cnx string) is quasi null.

I will prepare a PR now; we can release a 1.8.2 (this is really a small patch).
